version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git
    working_directory: /root/app
    steps:
      - checkout
      - run: apk update && apk add --update nodejs
      - run: node --version
